### ISSUE TITLE
Getting invalid syntax errror

### ISSUE THREAD

**Issue by irom77** [alerta/docker-alerta#125] opened 2019-04-23 17:43 UTC
See below:

``` 
File "/app/alertad.conf", line 5
    SLACK_WEBHOOK_URL = https://hooks.slack.com/services/xxx/xxx
                             ^
SyntaxError: invalid syntax
```

**Comment by satterly** [comment] 2019-04-23 20:20
Duplicate of alerta/alerta-contrib#257

**Closed by satterly** 2019-04-23 20:20 UTC
Labels: duplicate
